# Generated by Django 4.2.7 on 2023-12-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.RemoveField(
            model_name='sublinea',
            name='linea',
        ),
        migrations.DeleteModel(
            name='Linea',
        ),
        migrations.DeleteModel(
            name='Sublinea',
        ),
    ]
