# Generated by Django 4.2.7 on 2023-12-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0003_producto_condiciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='promociones_id',
            new_name='promocion_id',
        ),
    ]
